data:extend({
        {
            type = "bool-setting",
            name = "extend-bob-power",
            setting_type = "startup",
            default_value = true,
            order = "r",
			localised_name = "Extend BobPower",
			localised_description = "This enables or disables the late-tier solars and steam engines to extend bobpower. Does nothing without that mod installed.",
        },
        {
            type = "bool-setting",
            name = "free-use-modules",
            setting_type = "startup",
            default_value = true,
            order = "r",
			localised_name = "Unrestricted productivity modules",
			localised_description = "This makes the Tier-5 productivity modules have no restrictions on their use.",
        },
        {
            type = "bool-setting",
            name = "bigger-modules",
            setting_type = "startup",
            default_value = true,
            order = "r",
			localised_name = "Tier 4+ Modules",
			localised_description = "Should the upper-tier (4 and 5) modules be enabled?",
        },
        {
            type = "bool-setting",
            name = "fast-refinery",
            setting_type = "startup",
            default_value = false,
            order = "r",
			localised_name = "Enable Fast Refinery",
			localised_description = "Should the fast refineries be enabled?",
        },
        {
            type = "bool-setting",
            name = "fast-chemical",
            setting_type = "startup",
            default_value = false,
            order = "r",
			localised_name = "Enable Fast Chemical Plant",
			localised_description = "Should the fast chemical plants be enabled?",
        },
        {
            type = "bool-setting",
            name = "fast-furnace",
            setting_type = "startup",
            default_value = false,
            order = "r",
			localised_name = "Enable Fast Furnace",
			localised_description = "Should the fast (electric) furnaces be enabled?",
        },
        {
            type = "bool-setting",
            name = "fast-beacon",
            setting_type = "startup",
            default_value = true,
            order = "r",
			localised_name = "Enable Better Beacons",
			localised_description = "Should the better beacons be enabled?",
        },
        {
            type = "bool-setting",
            name = "fast-drill",
            setting_type = "startup",
            default_value = true,
            order = "r",
			localised_name = "Enable Improved Drills",
			localised_description = "Should the improved mining drills be enabled?",
        },
        {
            type = "bool-setting",
            name = "fast-pump",
            setting_type = "startup",
            default_value = true,
            order = "r",
			localised_name = "Enable Fast Pump",
			localised_description = "Should the fast pumps be enabled?",
        },
        {
            type = "bool-setting",
            name = "fast-long-inserter",
            setting_type = "startup",
            default_value = true,
            order = "r",
			localised_name = "Enable Fast Long Inserter",
			localised_description = "Should the fast long inserters (blue/red mix) be enabled?",
        },
        {
            type = "bool-setting",
            name = "bigger-chests",
            setting_type = "startup",
            default_value = true,
            order = "r",
			localised_name = "Enable Big Chests",
			localised_description = "Enable the bigger logistics chests?",
        },
})
